### PR TITLE
SPEC-536: Add note on guarantee of requestId

### PR DESCRIPTION
**Pull request by durran**

### CODE REVIEW

**Comment by behackett** [comment]
LGTM

**Comment by jyemin** [comment]
This is looser than I was expecting.  I see no reason a driver shouldn't not use the requestId for the corresponding wire protocol message sent to server.  In the case where the command event corresponds to multiple wire protocol messages, the driver should be free to pick any one of the messages, so long as the same one is used for both start and end/failed.  Some day the server may log request ids and if these events don't match what's in the logs it would be confusing.

**Comment by ajdavis** [comment]
So Jeff you're proposing that, in the acknowledged OP_INSERT case, a driver MUST use either the OP_INSERT's requestId, *or* the getLastError requestId, but not any other value than those two options? If so I concur.

**Comment by christkv** [comment]
I support Jeff on this one, the core idea of the requestId is to be able to correlate messages with possible log entries from the mongod processes.

**Comment by durran** [comment]
I'll update then. I got the feeling from the jira ticket we wanted this as loose as possible.

**Comment by durran** [comment]
@behackett @ajdavis @christkv @jyemin Updated.

**Comment by christkv** [comment]
LGTM

**Comment by jyemin** [comment]
LGTM

**Pull request merged**
