### PR TITLE
add horizon option

### PR DESCRIPTION
**Pull request by saghm**

### CODE REVIEW

**Comment by jmikola** [comment]
Can we get a spec ticket reference on this PR/commit?

**Comment by behackett** [comment]
I'm holding off on reviewing this until the related server design document is approved.

**Comment by xdg** [comment]
I'm involved in the server design review, so when that's done, we can revisit.  The option name is right, but the definition is incorrect.

**Comment by behackett** [comment]
We're not actually implementing this anymore, so I'm going to close this PR. Thanks @saghm .

**Pull request closed without merging**
