### PR TITLE
64-bit batchSize, skip, limit in command monitor tests.

### PR DESCRIPTION
**Pull request by ajdavis**
64-bit batchSize, skip, limit in command monitor tests.

### CODE REVIEW

**Comment by ajdavis** [comment]
@durran, this was necessary to make the C Driver's rather strict validation pass.

**Comment by ajdavis** [comment]
Hey @durran, permission to merge this?

**Comment by durran** [comment]
Thanks @ajdavis

**Comment by durran** [comment]
I'll add the changelog update.

**Pull request merged**
