### PR TITLE
refactor(change-streams): add exception for "cursor not found" error

### PR DESCRIPTION
**Pull request by mbroadst**
SPEC-903

### CODE REVIEW

**Comment by ajdavis** [comment]
Good, so far, but for implementors I recommend we specify how the driver parses these errors. I propose that a "not master" error is anything with "not master" in the error string (following SDAM) and that "cursor not found" is error code 43, ignoring the contents of the error message.

**Comment by jyemin** [comment]
I also suggest adding a specific integration test for this case, especially as it's easy to automate it (unlike "not master" errors).

**Comment by mbroadst** [comment]
@ajdavis @jyemin okay I'm into that, but does that belong in the definitions section anymore?

**Comment by jyemin** [comment]
You can put the specifics in the test case prose.

**Comment by ajdavis** [comment]
I'd say put it in the definitions section. A resumable error has error message that contains "not master" or has error code 43 (meaning cursor not found).

**Comment by mbroadst** [comment]
@jyemin @ajdavis updated the definitions section, as well as added an integration test

**Comment by jyemin** [comment]
LGTM

**Comment by ajdavis** [comment]
LGTM.

**Pull request merged**
