### PR TITLE
DRIVERS-2789 Add script to check for malformed links

### PR DESCRIPTION
**Pull request by blink1073**
Please complete the following before merging:

- [ ] Update changelog.
- [ ] Make sure there are generated JSON files from the YAML test files.
- [ ] Test changes in at least one language driver.
- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded
  clusters, and serverless).

### CODE REVIEW

**Review by dariakp — COMMENTED** [review]
just as a sanity check - could you add a commit to this PR with a broken link to demo it getting caught by this script?

**Comment by blink1073** [comment]
> just as a sanity check - could you add a commit to this PR with a broken link to demo it getting caught by this script?

I did that locally

**Comment by dariakp** [comment]
> > just as a sanity check - could you add a commit to this PR with a broken link to demo it getting caught by this script?
> 
> I did that locally

Of course, my thought was just that since these checks will run in GH on the PR itself, we have an opportunity to run the "test" in CI as well, capturing the red x next to the test commit for posterity, instead of just relying on local execution.

Anyway, that's fine. Is there any concern about this script accidentally catching distributed brackets in code snippets?

**Comment by blink1073** [comment]
> Of course, my thought was just that since these checks will run in GH on the PR itself, we have an opportunity to run the "test" in CI as well, capturing the red x next to the test commit for posterity, instead of just relying on local execution.

I've been using "rebase and merge" to make sure I don't miss the RST->MD renaming commit, and I don't want to accidentally forget to change it back after using a "squash and merge" on a PR.

> Is there any concern about this script accidentally catching distributed brackets in code snippets?

Good call, I'll add detection of whether we're in a code block.

**Comment by blink1073** [comment]
I verified this behavior locally as well.

**Review by dariakp — APPROVED** [review]

**Pull request merged**
