### PR TITLE
DRIVERS-2882 Add Kubernetes Support for OIDC

### PR DESCRIPTION
**Pull request by blink1073**
Please complete the following before merging:

- [x] Update changelog.
- [x] Make sure there are generated JSON files from the YAML test files.
- [x] Test changes in at least one language driver.
			https://github.com/mongodb/mongo-python-driver/pull/1759
- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded
  clusters, and serverless).

### CODE REVIEW

**Comment by blink1073** [comment]
Hey @durran, we're looking for a second implementer actually!  We can't test AKS until server 8.0.1 is available in Atlas, but otherwise  this is reviewable.  I see that is has a conflict, I'll update.

**Comment by blink1073** [comment]
https://github.com/mongodb/mongo-python-driver/pull/1759 is now passing for EKS and GKE.

**Comment by durran** [comment]
@blink1073 Ok thanks, I'll see if I can get this into Node on the weekend.

**Review by durran — APPROVED** [review]
Node impl: https://github.com/mongodb/node-mongodb-native/pull/4270

Not for others only to create one pod per type (eks, gke) per task group.

**Comment by durran** [comment]
All green as well for AKS on NODE. LGTM.

**Comment by blink1073** [comment]
All variants are currently passing in Python as well.

**Pull request merged**
