### PR TITLE
Clarify when to send a command's ReadConcern

### PR DESCRIPTION
**Pull request by kmahar**
I'm implementing `ReadConcern` for the Swift driver, and I found this section a bit confusing. I've updated it to clarify. This is how @mbroadst and I interpreted it, let us know if it's incorrect.

### CODE REVIEW

**Comment by jyemin** [comment]
@kmahar please close this PR.  Thanks!

**Comment by kmahar** [comment]
sorry, was waiting for a response from you, did you want me to merge it?

**Comment by mbroadst** [comment]
@jyemin was that an approval? We can merge this then

**Comment by jyemin** [comment]
My bad.  I didn't even notice I was on the approval list for this, and only commented because I saw it had been open for a while.

**Pull request merged**
