### PR TITLE
SPEC-930 Clarify OP_MSG Payload Type expectations

### PR DESCRIPTION
**Pull request by bjori**

### CODE REVIEW

**Comment by durran** [comment]
Can you update the changelog and the version as well please? 

https://github.com/mongodb/specifications/blob/master/source/command-monitoring/command-monitoring.rst#changelog

**Comment by jyemin** [comment]
I don't support this change as is.  

First, I don't think this spec should reference the wire protocol, as the spec is intended to be an abstraction of the wire protocol.

Second, implementers may require more freedom here.  Some might find it quite natural to continue to include the full document in the command started event (e.g. PyMongo), some might find it completely unnatural (e.g. C), and some might have to work a bit to preserve the current behavior (e.g. Java).

Third, the change as is doesn't really give any guidance.  Does 

    e.g. Payload Type=0 in OP_MSG.

mean that only including payload type 0 is one thing a driver could do, but it could also choose to do something else?

As an alternative, I would support a change which allowed, but did not require, an implementation to separate the payload 1 part of a command sent with OP_MSG into a separate property of the command started event.

**Comment by durran** [comment]
@jyemin Would changing the comment to be `Returns the command document` suffice? That seems to be the core focus from what I understand - it's a document object of some sort.

**Comment by bjori** [comment]
There are no implementation restrictions on how many payloads there could be, and there will be more payload type in the future.

At least, this new optional property would need to have `identifier`: `data` key-value pair. For future proving it, it would have to be an array of such pairs, but possible with the section id to boot?
I think it becomes quite complex very fast if we'd like to over inform the user of everything.
I'd rather opt for the performance hit of normalizing the message back into fully qualified command document

**Pull request closed without merging**
