### PR TITLE
Added test for legacy GridFS, where no filename was set

### PR DESCRIPTION
**Pull request by rozza**
SPEC-895

### CODE REVIEW

**Comment by ajdavis** [comment]
LGTM.

**Comment by mbroadst** [comment]
:+1:

**Comment by xdg** [comment]
I don't have time to review in detail but I like the idea of adding a test like this.

**Comment by jyemin** [comment]
@rstam please review or request a different reviewer.

**Comment by jyemin** [comment]
Ping @rstam

**Comment by rozza** [comment]
Rebased and merged.

**Pull request closed without merging**
