### PR TITLE
SPEC-1344 Add sleeps to make CMAP fairness test more reliable

### PR DESCRIPTION
**Pull request by ShaneHarvey**
See [SPEC-1344](https://jira.mongodb.org/browse/SPEC-1344) for an explanation.

### CODE REVIEW

**Comment by daprahamian** [comment]
Can we add a prose test to replace the removed spec test?

**Comment by mbroadst** [comment]
@ShaneHarvey I'm inclined to agree with @daprahamian on this one, is it difficult to implement a prose test for this?

**Comment by ShaneHarvey** [comment]
I don't know how we could implement a proper prose test either. Wouldn't the race condition described in SPEC-1344 also happen in a prose test?

**Comment by mbroadst** [comment]
the YAML test is confined by what we are able to do with the harness its working within. A prose test could simply require that you "prove" that the wait queue is "fair".

**Comment by ShaneHarvey** [comment]
I've updated to keep the test in place but added some sleeps to make the test more reliable.

**Pull request merged**
