### PR TITLE
Remove conflicts between Extended JSON and the MongoDB query language

### PR DESCRIPTION
**Pull request by jyemin**

### CODE REVIEW

**Comment by behackett** [comment]
I suspect this will also be a backward breaking change for the mongo tools.

**Comment by jyemin** [comment]
The backwards compatibility implications are similar to those in the 1.0.0 version of the spec: for example, the change to $timestamp.  

I hesitate to make anything about handling $regex normative.  Consider the following cases:

- A new library with no backwards compatibility concerns would not have to special-case $regex at all.  It's just one more $-prefixed key that it treats as nothing special.
- The mongoimport and mongoexport tools do not attempt to provide backward compatibility across versions: so the 3.4 version will generate and parse $regex (and of course care not about $regularExpression), while the 3.6 version will generate and parse $regularExpression (and care not about $regex)
- an existing library has several implementation choices for backwards compatibility
-- Introduce a JsonMode enumeration that determines the behavior of the parser and the generator.  If the value is LEGACY, it will generate/parse $regex and not treat $regularExpression specially, and if the value is CANONICAL, it will generate/parse $regularExpression and not treat $regex specially.
-- Introduce a JsonMode enumeration for the generator but support _all_ modes when parsing.  This is the trickiest case, and making it work for the $regex query operator use case will require that the rules set forth in the 1.0.0 version of the spec are followed for $regex; specifically, that a $regex key with a value that's a document should be treated as a normal document.  This will allow `{\"$regex\" : {\"$regularExpression\" : { \"pattern\": \"pattern\", \"options\" : \"\"}}, \"$options\" : \"ix\"}` to be parsed.

I don't think we have to mandate one choice or another in the spec, but if you're amenable I can put this in the Q&A.   Let me know.

**Comment by ajdavis** [comment]
OK, could you put a MAY in the spec to allow deviations in parsing `$regex` and a Q & A that explains the history and reasoning? I'm comfortable letting the maintainers of individual tools and drivers deal with this as they see fit, based on their own needs, especially if that choice lets us finish this spec. But I think an explanation in the Q & A about what formats exist in the wild will help us make informed decisions.

**Comment by jyemin** [comment]
* Added a MUST about the requirement to parse a $regex query operator, as there are actually tests that require it (and added a second test)
* Added a Q&A about how one might implemented a parser that handled both Legacy and Canonical representations of regular expressions.
* Changed the language to use "regular expression instead of "regex"

**Comment by Joannis** [comment]
If I may ask, what is the motivation from moving from `$regex` to `$regularExpression`?

**Comment by jyemin** [comment]
The motivation is a conflict between usage of $regex to represent a BSON regular expression in extended JSON and usage to represent the MongoDB [regex query operator](https://docs.mongodb.com/manual/reference/operator/query/regex/).  The goal is that tools are able to parse any aggregation pipeline represented as extended JSON.

**Comment by ajdavis** [comment]
Jeff, should these cases still be in "parseErrors" in top.json?:
```
{
    "description" : "Nested document that resembles extjson, but with extra keys",
    "string" : "{\"a\":{\"$regex\":\"abc\",\"$options\":\"\",\"unrelated\":true}}"
},
{
    "description" : "Nested document that resembles extjson, but with missing keys",
    "string" : "{\"a\":{\"$regex\":\"abc\"}}"
},
```
Or should they be moved to "valid" in top.json? Or not tested at all?

**Comment by jyemin** [comment]
Hi Jesse, 

Thanks for finding these errors.  I've added a patch:

* Moved DBPointer parseErrors to top.json, grouped with the rest of the extended JSON parse errors
* Removed the two valid tests in top.json.  The $regex one is covered in regex.json, and the $binary one should actually be a parse error
* Changed the $regex parse error tests to $regularExpression
* Added a bunch of new extra and missing field parse error tests for every type, to round out the test coverage.  I'd appreciate if someone checks to see these pass, as currently the Java driver is failing most of these, as I haven't yet updated the implementation to match the new required spec behavior.

**Comment by ajdavis** [comment]
Checking against libbson now....

**Comment by ajdavis** [comment]
The same libbson code that passed my edited version of the tests yesterday also passes your version of the tests now. LGTM.

**Comment by jyemin** [comment]
@xdg if you approve you can just merge this.

**Comment by jyemin** [comment]
OK, bit of bad news.  In getting these tests to pass in the Java driver, I discovered another, similar, problem, this time with the extended JSON form of binary: the $type field conflicts with the [$type query operator](https://docs.mongodb.com/manual/reference/operator/query/type/).  

I have a patch on my Java driver branch that changes the binary form to:

    {$binary : {hex : "AQID", subType : "00"} }

I don't relish this change, but I also don't see another way forward given the strict parsing rules of the revised spec.

**Comment by ajdavis** [comment]
Eww. OK, go ahead and change that too.

**Comment by ShaneHarvey** [comment]
Can you provide an example query or aggregation pipeline which conflicts with the current `{$binary: "", $type: ""}` format?

**Comment by jyemin** [comment]
This would be enough to trigger an error

     {"someField : { "$type : "string" } }

This is due to this language in the revised specification

> If the parsed object contains any of the special **keys** in the Conversion table such as ``"$binary"``, ``"$timestamp"``, etc., then it must contain exactly the keys of a type wrapper. Any missing or extra keys constitute an error.

**Comment by ShaneHarvey** [comment]
Thanks, I missed the bit about stricter parsing for missing and extra keys.

**Comment by jyemin** [comment]
Added patch to tests reflecting the proposed change to the form for the binary type.   If this looks good I'll update the spec next.

**Comment by ajdavis** [comment]
LGTM, I've updated libbson to pass these.

**Comment by jyemin** [comment]
Tests updated to use "base64" rather than "hex" for binary data.  Thanks @xdg for spotting that oversight. 
Specification updated to reflect the change in binary form.

**Comment by ajdavis** [comment]
LGTM

**Pull request closed without merging**
