### PR TITLE
DRIVERS-2449: Do not connect to mongocryptd if shared library is loaded

### PR DESCRIPTION
**Pull request by DmitryLukyanov**
Please complete the following before merging:
- [ ] Bump spec version and last modified date.
- [ ] Update changelog.
- [ ] Make sure there are generated JSON files from the YAML test files.
- [ ] Test changes in at least one language driver.
- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).

### CODE REVIEW

**Review by kevinAlbs — COMMENTED** [review]
The changes have been implemented in Go.

Here is a [proposed prose test](https://github.com/mongodb/mongo-go-driver/pull/1082/files#diff-55617555c17bae6fadeb3e9a0c0e3a10837496998c75937eba67712b871f58eeR1994-R2036). It requires starting a connection listener in a separate goroutine. Does this test look OK for C#?

**Comment by kevinAlbs** [comment]
Also, please "Bump spec version and last modified date." and "Update changelog".

**Comment by DmitryLukyanov** [comment]
> The changes have been implemented in Go.
> 
> Here is a [proposed prose test](https://github.com/mongodb/mongo-go-driver/pull/1082/files#diff-55617555c17bae6fadeb3e9a0c0e3a10837496998c75937eba67712b871f58eeR1994-R2036). It requires starting a connection listener in a separate goroutine. Does this test look OK for C#?

looks interesting, I will check whether it will work.

**Comment by DmitryLukyanov** [comment]
Yes, I think it should work, this is how it will look in c# https://github.com/DmitryLukyanov/mongo-csharp-driver/tree/drivers2449. I will update this PR on the next week

**Comment by kevinAlbs** [comment]
Closing in favor of https://github.com/mongodb/specifications/pull/1330

**Pull request closed without merging**
