### PR TITLE
Change the required MongoDB version to 4.9.0+ in the "Connection Pool Management" test

### PR DESCRIPTION
**Pull request by stIncMale**
DRIVERS-1650

### CODE REVIEW

**Review by patrickfreed — COMMENTED** [review]
appName support actually was added to failCommand in 4.2.9, however it has a bug that causes it to not work on initial handshake `isMaster` / `hello` commands until 4.9, which is why some other tests require 4.9. This test in particular only triggers the failpoint on post-handshake `isMaster` commands though, which means it can run on 4.2.9+. I updated the [failCommand wiki page](https://github.com/mongodb/mongo/wiki/The-%22failCommand%22-fail-point) to reflect this information.

**Comment by stIncMale** [comment]
@patrickfreed Thank you for the details! Is my understanding correct that your answer implies that we need to close the PR?

**Comment by patrickfreed** [comment]
I personally think the test is fine as-is and we can close the PR, though if you think it will cause similar confusion in the future, maybe its worth updating.

**Comment by stIncMale** [comment]
Then I am closing it.

**Pull request closed without merging**
