### PR TITLE
test(benchmark): update extended bson tests to extended json 2.0

### PR DESCRIPTION
**Pull request by daprahamian**
Adds the 2.0 extended json, and moves the old extended json to `extended_bson_legacy.tgz`

### CODE REVIEW

**Comment by mbroadst** [comment]
Is there a reason we are keeping the tests in a tarball? Why not extract the folder and commit the files

**Comment by xdg** [comment]
The files are large and have a lot of repetitive data, so keeping it tarred and compressed makes it manageable.  
Next week I'll download the new tarball and review offline.

**Comment by mbroadst** [comment]
@xdg ping

**Comment by xdg** [comment]
This section of diff from full_bson.json seems to have dropped the regex item:
```
    "BOQAeydE" : {
-      "$binary" : "RWNVVkhUUmVsWEhzcnhxV25WdnVQTWFERUJMRFRrYmlOVUFGYmh3QWZzRGtTRkVHT1lrTWFKR2twUUFIZVVGWkJ1Y1RlYlpNTGF2VG51Vk8=",
-      "$type" : "00"
-   },
-   "BZogAEUM" : {
-      "$options" : "",
-      "$regex" : "luJBIsSO"
+      "$binary" : {
+         "base64" : "RWNVVkhUUmVsWEhzcnhxV25WdnVQTWFERUJMRFRrYmlOVUFGYmh3QWZzRGtTRkVHT1lrTWFKR2twUUFIZVVGWkJ1Y1RlYlpNTGF2VG51Vk8=",
+         "subType" : "00"
+      }
    },
+   "BZogAEUM" : {},
```

**Comment by xdg** [comment]
This one swaps i and t:
```
    "LNpbbRfA" : {
       "$timestamp" : {
-         "i" : 1,
-         "t" : 808444800
+         "i" : 808444800,
+         "t" : 1
       }
```

This has both the blank regex and the swapped timestamp
```
-   "ZZbaMgQp" : {
-      "$options" : "",
-      "$regex" : "uWxyRVYi"
-   },
+   "ZZbaMgQp" : {},
    "ZmCYgzpS" : {
       "$timestamp" : {
-         "i" : 1,
-         "t" : 923788800
+         "i" : 923788800,
+         "t" : 1
       }
    },
```

**Comment by xdg** [comment]
Other than those nits, LGTM.

**Comment by daprahamian** [comment]
Updated to include @xdg feedback

**Comment by mbroadst** [comment]
abstain

**Comment by ajdavis** [comment]
Let's merge this.

**Comment by p-mongo** [comment]
These files are only 24k untarred, but because json there is not pretty printed it's indeed not very readable. Perhaps pretty printing json (and committing it untarred) would be a good first step?

**Comment by mbroadst** [comment]
@xdg please review and approve if possible, I think we can just merge. I think the fact that it has taken this long proves my initial point about extracting the tar files - seems like it would have taken no time at all to see the diffs, and anybody could have approved.

**Comment by xdg** [comment]
I already said LGTM other than nits. I didn't see any point in re-reviewing.  I have no problem with text files in the repo if someone wants to make that change.

**Comment by mbroadst** [comment]
@xdg I think the confusion is coming from you being a "requested reviewer" here, but not having added your approval through github.

**Pull request merged**
