### PR TITLE
DRIVERS-1649 acceptAPIVersion2 -> acceptApiVersion2

### PR DESCRIPTION
**Pull request by kmahar**
https://jira.mongodb.org/browse/DRIVERS-1649

The server renamed this parameter.

### CODE REVIEW

**Review by alcaeus — APPROVED** [review]
LGTM, thanks!

**Comment by kmahar** [comment]
@alcaeus, good catch, done... should I update the spec version too? I'm not really sure how one would classify this change under semver 🤔

**Comment by alcaeus** [comment]
Tough one...because it seems like a breaking change. Since it's based on a server change I think we should increase the patch version and call it a day.

**Comment by kmahar** [comment]
sgtm. done

**Pull request merged**
