### PR TITLE
SPEC-634: added RSOther into the list of server types that must be au…

### PR DESCRIPTION
**Pull request by craiggwilson**
…thenticated.

---

This change is [Reviewable](https://reviewable.io/reviews/mongodb/specifications/98)

### CODE REVIEW

**Comment by xdg** [comment]
In the ticket, I proposed always doing auth for topology type Single.  This is different, as it will do auth on RSOther for replica sets.

I'm worried that could have unpredictable adverse effects, possibly including more connection churn if auth fails.  (I.e. RSOther gets marked Unknown and requires reconnection on next scan.)  It's probably safe, but I'd prefer the narrower "Single" only approach.

@ajdavis, I'd welcome your thoughts on this issue of auth to RSOther in replica sets.

**Comment by craiggwilson** [comment]
Sorry, I comment on the ticket itself, should have done that here. If we do Topology Type Single, that would include Arbiters. So, we'd have to say something about excluding arbiters while including the other things. Ultimately, in theory, we could revers the list and say that everything should be authenticated *except* for arbiters...

**Comment by xdg** [comment]
Missed that it was on the Jira ticket.  Let's move the conversation there for posterity.  I'll copy/paste it.

**Comment by bjori** [comment]
Closed in favor of https://github.com/mongodb/specifications/pull/176 which fixes the now-conflicts and remves 'unknown' from the list of not-to-authenticate.

**Pull request closed without merging**
