### PR TITLE
DRIVERS-2203: Rename Versioned API to Stable API

### PR DESCRIPTION
**Pull request by jmikola**
https://jira.mongodb.org/browse/DRIVERS-2203

### CODE REVIEW

**Review by comandeo — APPROVED** [review]
LGTM
I searched through all files in the project, and the only leftovers of the word 'versioned' are in file names or spec tests.
I am not sure whether such a terminology change deserves version bump, but I am not against this bump.

**Comment by jmikola** [comment]
> I am not sure whether such a terminology change deserves version bump, but I am not against this bump.

I concur. These are all patch bumps, which would be what would otherwise be used for small changes like typos.

Separately, I think we should revisit the idea of spec versioning. There are places where it definitely makes sense (e.g. unified test format with schema), but with some of the recent PRs I've worked on I'm not convinced it's adding any value. A number of older specs (e.g. CRUD) don't have a version and I'm not aware of any drivers actually relying on these spec versions (e.g. advertising that they comply with version X.Y of some spec). That's a task for a later day, though.

**Review by nbbeeken — COMMENTED** [review]
Just to keep us all on the same page, I left a comment on DRIVERS-2203 relating to taking this work further to cover the drivers changes needed work of renaming the files/directory and making the changes inside the tests.

**Comment by jmikola** [comment]
> Just to keep us all on the same page, I left a comment on [DRIVERS-2203](https://jira.mongodb.org/browse/DRIVERS-2203) relating to taking this work further to cover the drivers changes needed work of renaming the files/directory and making the changes inside the tests.

Reported [DRIVERS-2216](https://jira.mongodb.org/browse/DRIVERS-2216) to track that, per @behackett's request.

**Pull request merged**
