### PR TITLE
DRIVERS-2493 Ensure Auth Environment Variables are Always Dynamic

### PR DESCRIPTION
**Pull request by blink1073**
Please complete the following before merging:

- [x] Update changelog.
- [ ] Make sure there are generated JSON files from the YAML test files.
- [x] Test changes in at least one language driver.
- [x] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).

### CODE REVIEW

**Review by DmitryLukyanov — APPROVED** [review]
Question: can we think about a test, maybe prose test here?
Other than above, LGTM

**Review by JamesKovacs — APPROVED** [review]
LGTM

**Comment by blink1073** [comment]
Tests are implemented in https://github.com/mongodb/mongo-python-driver/pull/1107

**Review by DmitryLukyanov — APPROVED** [review]
LGTM (c# [impl)](https://github.com/mongodb/mongo-csharp-driver/pull/933)

**Review by JamesKovacs — APPROVED** [review]
LGTM

**Pull request merged**
