### PR TITLE
SPEC-311: Remove tests around failures with ok:1

### PR DESCRIPTION
**Pull request by durran**

### CODE REVIEW

**Comment by craiggwilson** [comment]
This is fine for now, but we still need failure tests.

**Comment by jyemin** [comment]
I don't think these tests should be removed.  I'd rather see them turned into tests that assert that write errors result in command succeeded events.

As for failure tests, I don't know of a way to make a write command/GLE return ok : 0.  I couldn't find any test coverage in the Java driver for this.

**Comment by durran** [comment]
@jyemin @craiggwilson With the error messages being different depending on the server versions, should the expectation in this case only contain the `{ ok: 1.0 }`?

**Comment by durran** [comment]
Will reopen with new pull.

**Pull request closed without merging**
