### PR TITLE
SPEC-1061: Add server reply to CommandFailedEvent

### PR DESCRIPTION
**Pull request by kvwalker**
https://jira.mongodb.org/browse/SPEC-1061

### CODE REVIEW

**Comment by mbroadst** [comment]
I would prefer not to add this, or at least to make the field optional. Generally the `failure` field is sufficient for drivers, however I understand in this case having libmongoc include a `reply` field was useful so the PHP driver could continue to create fully detailed exceptions for their own `failure` field. In this case, I think it does help other drivers if libmongoc includes this field but we should not specify the behavior for all drivers.

**Comment by ajdavis** [comment]
Great. Could you add or update some of the failure tests here in source/command-monitoring/tests/? Make sure that drivers are properly filling out the "reply" document. Update the README there to describe how driver tests should handle the error reply - probably adapt the "errors" paragraph. Currently that paragraph describes how tests should handle writeError subdocuments within a command-succeeded event, you can expand it to also describe how to handle the reply document of a command-failed event.

**Comment by ajdavis** [comment]
Matt I disagree, I think that drivers should strive, if at all possible, to implement all the specs the same way. First, because if the feature is useful in C then it's probably useful everywhere, and second, because consistency is inherently valuable. There's no programming-language reason or other fundamental difference among drivers that prevents us all from including the server error reply in command-failed events, so let's all do it identically.

**Comment by kvwalker** [comment]
After discussing with Jesse, the spec is fine as is.

**Pull request closed without merging**
