### PR TITLE
Add serverless: forbid for collection management tests

### PR DESCRIPTION
**Pull request by jyemin**
Please complete the following before merging:
- [n/a] Bump spec version and last modified date.
- [n/a] Update changelog.
- [x] Make sure there are generated JSON files from the YAML test files.
- [x] Test changes in at least one language driver.
- [x] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).

Not sure why this wasn't caught in initial testing, but serverless tests are failing in Java driver.

### CODE REVIEW

**Comment by jyemin** [comment]
Java runs all unified tests on serverless, and relies on runOnRequirements to restrict.  Everyone should do this IMO.

> I think you should also forbid serverless on timeseries-collection and modifyCollection-pre_and_post_images, too

Those tests are not failing so I didn't change them.  Is time series not supported on serverless? I don't know why modify... is succeeded, but it seems to be.

**Comment by jyemin** [comment]
Added serverless restriction to modify collection test

**Review by benjirewis — APPROVED** [review]
Thanks! LGTM

**Comment by jmikola** [comment]
@jyemin: Was there a DRIVERS ticket for this change? I assume the new commit will be relevant for drivers to sync to.

If there will be a ticket created for this, I think it'd also be a good opportunity to knock out [DRIVERS-2325](https://jira.mongodb.org/browse/DRIVERS-2325) since the same test file will be synced.

**Pull request merged**
